

services:
  db:
    image: postgres:16.3-alpine3.18
    # mounting the below created volume to /var/lib/postgresql/data/,
    # as in linux this is the place where postgresql fetches its data from.
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev 

  daphne:
    build: .
    command: daphne --bind 0.0.0.0 -p 8002 djangobnb.asgi:application
    ports:
      - 8002:8002
    volumes:
      - .:/app
    env_file:
      - ./.env.dev

  api:
    build: .
    command: gunicorn djangobnb.wsgi:application --bind 0.0.0.0:8000
    # mounting all the file in bnb.backend to app dir as my workdir for docker is app
    volumes:
      - .:/app
      - media:/app/media/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - daphne

  nginx:
    build: ./nginx
    volumes:
      - ./static/:/app/static/
      - media:/app/media/
    ports:
      - 1337:80 # host:container host is my mac, container is docker container in this case it is nginx.
    depends_on:
      - api


# here creating a docker volume
volumes:
  postgres_data:
  media:
